package Views;

import Controllers.BukuController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author aliad
 */
public class HomeView extends javax.swing.JFrame {
    BukuController controllerBuku;

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        controllerBuku = new BukuController(this);
        controllerBuku.loadDataTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataBuku = new javax.swing.JTable();
        txtCariBuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbKategoriCari = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPenulis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERPUSTAKAAN UMUM KOS KUNING");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1080, -1));

        tabelDataBuku.setBackground(new java.awt.Color(255, 255, 255));
        tabelDataBuku.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tabelDataBuku.setForeground(new java.awt.Color(0, 0, 0));
        tabelDataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Buku", "Judul Buku", "Genre", "Penulis", "Penerbit", "Lokasi", "Stock"
            }
        ));
        tabelDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataBuku);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 640, 400));

        txtCariBuku.setBackground(new java.awt.Color(255, 255, 255));
        txtCariBuku.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtCariBuku.setForeground(new java.awt.Color(0, 0, 0));
        txtCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariBukuActionPerformed(evt);
            }
        });
        jPanel1.add(txtCariBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 210, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cari Buku :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 70, 40));

        cbKategoriCari.setBackground(new java.awt.Color(255, 255, 255));
        cbKategoriCari.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cbKategoriCari.setForeground(new java.awt.Color(0, 0, 0));
        cbKategoriCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Judul", "Genre", "Penulis", "Penerbit" }));
        cbKategoriCari.setSelectedIndex(-1);
        cbKategoriCari.setToolTipText("");
        cbKategoriCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriCariActionPerformed(evt);
            }
        });
        jPanel1.add(cbKategoriCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, -1));

        btnCari.setBackground(new java.awt.Color(51, 51, 255));
        btnCari.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(0, 0, 0));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Stock");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 60, 30));

        txtStock.setBackground(new java.awt.Color(255, 255, 255));
        txtStock.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtStock.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 200, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID Buku");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(153, 153, 153));
        txtID.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 200, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Judul");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 40, 30));

        txtJudul.setBackground(new java.awt.Color(255, 255, 255));
        txtJudul.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtJudul.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Genre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 40, 30));

        txtGenre.setBackground(new java.awt.Color(255, 255, 255));
        txtGenre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtGenre.setForeground(new java.awt.Color(0, 0, 0));
        txtGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreActionPerformed(evt);
            }
        });
        jPanel1.add(txtGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 200, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Penulis");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 50, 30));

        txtPenulis.setBackground(new java.awt.Color(255, 255, 255));
        txtPenulis.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtPenulis.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 200, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Penerbit");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 60, 30));

        txtPenerbit.setBackground(new java.awt.Color(255, 255, 255));
        txtPenerbit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtPenerbit.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 200, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Lokasi");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 60, 30));

        txtLokasi.setBackground(new java.awt.Color(255, 255, 255));
        txtLokasi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtLokasi.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 200, 30));

        btnTambah.setBackground(new java.awt.Color(51, 255, 0));
        btnTambah.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(0, 0, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        btnEdit.setBackground(new java.awt.Color(0, 51, 255));
        btnEdit.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        btnShowAll.setBackground(new java.awt.Color(255, 255, 255));
        btnShowAll.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnShowAll.setForeground(new java.awt.Color(0, 0, 0));
        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariBukuActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        controllerBuku.editDataTabel();
        controllerBuku.loadDataTabel();
        clearField();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        controllerBuku.deleteDataTabel();
        controllerBuku.loadDataTabel();
        clearField();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        controllerBuku.insertDataTabel();
        controllerBuku.loadDataTabel();
        clearField();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tabelDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataBukuMouseClicked
        int row = tabelDataBuku.getSelectedRow();
        txtID.setText(tabelDataBuku.getValueAt(row, 0).toString());
        txtJudul.setText(tabelDataBuku.getValueAt(row, 1).toString());
        txtGenre.setText(tabelDataBuku.getValueAt(row, 2).toString());
        txtPenulis.setText(tabelDataBuku.getValueAt(row, 3).toString());
        txtPenerbit.setText(tabelDataBuku.getValueAt(row, 4).toString());
        txtLokasi.setText(tabelDataBuku.getValueAt(row, 5).toString());
        txtStock.setText(tabelDataBuku.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tabelDataBukuMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String keyword = txtCariBuku.getText();
        Object selectedKategori = cbKategoriCari.getSelectedItem();
       
        String kategori = (selectedKategori == null) ? "judul" : selectedKategori.toString();
        controllerBuku.searchDataTabel(keyword, kategori);
    }//GEN-LAST:event_btnCariActionPerformed

    private void cbKategoriCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKategoriCariActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        controllerBuku.loadDataTabel();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearField();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbKategoriCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataBuku;
    private javax.swing.JTextField txtCariBuku;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCari() {
        return btnCari;
    }

    public void setBtnCari(JButton btnCari) {
        this.btnCari = btnCari;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public void setBtnEdit(JButton btnEdit) {
        this.btnEdit = btnEdit;
    }

    public JButton getBtnHapus() {
        return btnHapus;
    }

    public void setBtnHapus(JButton btnHapus) {
        this.btnHapus = btnHapus;
    }

    public JButton getBtnShowAll() {
        return btnShowAll;
    }

    public void setBtnShowAll(JButton btnShowAll) {
        this.btnShowAll = btnShowAll;
    }

    public JButton getBtnTambah() {
        return btnTambah;
    }

    public void setBtnTambah(JButton btnTambah) {
        this.btnTambah = btnTambah;
    }

    public JComboBox<String> getCbKategoriCari() {
        return cbKategoriCari;
    }

    public void setCbKategoriCari(JComboBox<String> cbKategoriCari) {
        this.cbKategoriCari = cbKategoriCari;
    }

    public JTable getTabelDataBuku() {
        return tabelDataBuku;
    }

    public void setTabelDataBuku(JTable tabelDataBuku) {
        this.tabelDataBuku = tabelDataBuku;
    }

    public JTextField getTxtCariBuku() {
        return txtCariBuku;
    }

    public void setTxtCariBuku(JTextField txtCariBuku) {
        this.txtCariBuku = txtCariBuku;
    }

    public JTextField getTxtGenre() {
        return txtGenre;
    }

    public void setTxtGenre(JTextField txtGenre) {
        this.txtGenre = txtGenre;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public void setTxtID(JTextField txtID) {
        this.txtID = txtID;
    }

    public JTextField getTxtJudul() {
        return txtJudul;
    }

    public void setTxtJudul(JTextField txtJudul) {
        this.txtJudul = txtJudul;
    }

    public JTextField getTxtLokasi() {
        return txtLokasi;
    }

    public void setTxtLokasi(JTextField txtLokasi) {
        this.txtLokasi = txtLokasi;
    }

    public JTextField getTxtPenerbit() {
        return txtPenerbit;
    }

    public void setTxtPenerbit(JTextField txtPenerbit) {
        this.txtPenerbit = txtPenerbit;
    }

    public JTextField getTxtPenulis() {
        return txtPenulis;
    }

    public void setTxtPenulis(JTextField txtPenulis) {
        this.txtPenulis = txtPenulis;
    }

    public JTextField getTxtStock() {
        return txtStock;
    }

    public void setTxtStock(JTextField txtStock) {
        this.txtStock = txtStock;
    }
    
    public void clearField(){
        txtID.setText("");
        txtJudul.setText("");
        txtGenre.setText("");
        txtPenulis.setText("");
        txtPenerbit.setText("");
        txtLokasi.setText("");
        txtStock.setText("");
    }
}
